### ISSUE TITLE
Error in demo when factoring 2^127-2

### ISSUE THREAD

**Issue by shreevatsa** [Yaffle/QuadraticSieveFactorization#3]
Steps to reproduce: 

- At https://yaffle.github.io/QuadraticSieveFactorization/demo.html enter `2**127 - 2` or `170141183460469231731687303715884105726`.
- Hit Enter or click Go

Result:

<img width="813" alt="image" src="https://github.com/Yaffle/QuadraticSieveFactorization/assets/767530/d0c98ce2-6cfe-4261-9ef4-8acd2d2255ba">

----

From looking at the console:

<img width="884" alt="image" src="https://github.com/Yaffle/QuadraticSieveFactorization/assets/767530/a5b8793e-0e73-4913-be8e-b987f926c2ca">

the error seems to be coming from this line:
 https://github.com/Yaffle/QuadraticSieveFactorization/blob/12e11400d0f808f008f8991895de14c6ecc7c31c/QuadraticSieveFactorization.js#L1165-L1167

**Comment by Yaffle** [comment]
Thanks
it seems it happens during factorization of 3520491283

**Comment by Yaffle** [comment]
It should be fixed now
